server:
  port: 65432
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/OppProject?createDatabaseIfNotExist=true
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: admin
      password: admin
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        cache:
          use_second_level_cache: false
        format_sql: true
    database: mysql
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQLDialect

  # MongoDB Configuration
  data:
    mongodb:
      uri: mongodb://localhost:27017/NGResearch  # MongoDB URI
      auto-index-creation: true

